// Computed goto array for threaded dispatch
// This maps bytecodes to label addresses for fast dispatch
static constexpr void *computed_opcode[] = {
	[LA64_BC_INVALID]   = &&execute_invalid,
	[LA64_BC_LD_D]      = &&la64_ld_d,
	[LA64_BC_OR]        = &&la64_or,
	[LA64_BC_ST_D]      = &&la64_st_d,
	[LA64_BC_ADDI_W]    = &&la64_addi_w,
	[LA64_BC_ADDI_D]    = &&la64_addi_d,
	[LA64_BC_ANDI]      = &&la64_andi,
	[LA64_BC_ADD_D]     = &&la64_add_d,
	[LA64_BC_SUB_D]     = &&la64_sub_d,
	[LA64_BC_ORI]       = &&la64_ori,
	[LA64_BC_SLLI_W]    = &&la64_slli_w,
	[LA64_BC_SLLI_D]    = &&la64_slli_d,
	[LA64_BC_LD_BU]     = &&la64_ld_bu,
	[LA64_BC_ST_B]      = &&la64_st_b,
	[LA64_BC_PCADDI]    = &&la64_pcaddi,
	[LA64_BC_PCALAU12I] = &&la64_pcalau12i,
	[LA64_BC_LDPTR_D]   = &&la64_ldptr_d,
	[LA64_BC_LDPTR_W]   = &&la64_ldptr_w,
	[LA64_BC_STPTR_D]   = &&la64_stptr_d,
	[LA64_BC_LU12I_W]   = &&la64_lu12i_w,
	[LA64_BC_B]         = &&la64_b,
	[LA64_BC_BL]        = &&la64_bl,
	[LA64_BC_BEQZ]      = &&la64_beqz,
	[LA64_BC_BNEZ]      = &&la64_bnez,
	[LA64_BC_BEQ]       = &&la64_beq,
	[LA64_BC_BNE]       = &&la64_bne,
	[LA64_BC_BLT]       = &&la64_blt,
	[LA64_BC_BGE]       = &&la64_bge,
	[LA64_BC_BLTU]      = &&la64_bltu,
	[LA64_BC_BGEU]      = &&la64_bgeu,
	[LA64_BC_FUNCTION]  = &&execute_decoded_function,
	[LA64_BC_FUNCBLOCK] = &&execute_function_block,
	[LA64_BC_SYSCALL]   = &&la64_syscall,
	[LA64_BC_STOP]      = &&la64_stop,
};
